name: "funny-deploy"
description: "deploy your project to the server via ssh password"
author: "BoatNg"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "orange"
  icon: "upload-cloud"
