on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy test
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: deploy
        id: funny-deploy
        uses: BoatNg/funny-deploy@master
        env:
          REMOTE_HOST: "${{ secrets.REMOTE_HOST }}"
          REMOTE_USER: "${{ secrets.REMOTE_USER }}"
          REMOTE_PASSWORD: "${{ secrets.REMOTE_PASSWORD }}"
          REMOTE_PATH: "/home/www/deploy-action"
          SOURCE: "dist/"